[build]
  base = "frontend"
  publish = ".next"
  command = "npm run build"

[functions]
  directory = "../backend/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200